# Generated by Django 3.1.1 on 2020-09-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='homepage',
        ),
    ]
